repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: double-quote-string-fixer

  - repo: https://github.com/prettier/prettier
    rev: 2.0.5
    hooks:
      - id: prettier
  # - repo: https://github.com/deathbeds/prenotebook
  #   rev: f5bdb72a400f1a56fe88109936c83aa12cc349fa
  #   hooks:
  #     - id: prenotebook
  #       args:
  #         [
  #           "--keep-output",
  #           "--keep-metadata",
  #           "--keep-execution-count",
  #           "--keep-empty",
  #         ]
